version: "3"
services:
  onboardingdb:
    image: postgres:12.9
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
